networks:
  chess-network:

services:
  chess:
    build:
      context: ./chess
      dockerfile: Dockerfile
    networks:
      - chess-network
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"

  chess-web:
    build:
      context: ./ChessWeb
      dockerfile: Dockerfile
    networks:
      - chess-network
    environment:
      - CONTROLLER_URL=http://chess:8081/controller
      - LEGALITY_URL=http://chess:8082
    ports:
      - "9000:9000"
    depends_on:
      - chess